/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FundTransparencyInterface extends Interface {
  getFunction(
    nameOrSignature: "recordDisbursement" | "recordDonation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DisbursementRecorded" | "DonationRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "recordDisbursement",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDonation",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordDisbursement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDonation",
    data: BytesLike
  ): Result;
}

export namespace DisbursementRecordedEvent {
  export type InputTuple = [
    campaignId: string,
    amount: BigNumberish,
    reportHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    amount: bigint,
    reportHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    amount: bigint;
    reportHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationRecordedEvent {
  export type InputTuple = [
    campaignId: string,
    amount: BigNumberish,
    dataHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    amount: bigint,
    dataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    amount: bigint;
    dataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundTransparency extends BaseContract {
  connect(runner?: ContractRunner | null): FundTransparency;
  waitForDeployment(): Promise<this>;

  interface: FundTransparencyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordDisbursement: TypedContractMethod<
    [campaignId: string, amount: BigNumberish, reportHash: string],
    [void],
    "nonpayable"
  >;

  recordDonation: TypedContractMethod<
    [campaignId: string, amount: BigNumberish, dataHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordDisbursement"
  ): TypedContractMethod<
    [campaignId: string, amount: BigNumberish, reportHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordDonation"
  ): TypedContractMethod<
    [campaignId: string, amount: BigNumberish, dataHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisbursementRecorded"
  ): TypedContractEvent<
    DisbursementRecordedEvent.InputTuple,
    DisbursementRecordedEvent.OutputTuple,
    DisbursementRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DonationRecorded"
  ): TypedContractEvent<
    DonationRecordedEvent.InputTuple,
    DonationRecordedEvent.OutputTuple,
    DonationRecordedEvent.OutputObject
  >;

  filters: {
    "DisbursementRecorded(string,uint256,string,uint256)": TypedContractEvent<
      DisbursementRecordedEvent.InputTuple,
      DisbursementRecordedEvent.OutputTuple,
      DisbursementRecordedEvent.OutputObject
    >;
    DisbursementRecorded: TypedContractEvent<
      DisbursementRecordedEvent.InputTuple,
      DisbursementRecordedEvent.OutputTuple,
      DisbursementRecordedEvent.OutputObject
    >;

    "DonationRecorded(string,uint256,string,uint256)": TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
    DonationRecorded: TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
  };
}
